repos:
- repo: https://github.com/python-poetry/poetry
  rev: '1.2.2'
  hooks:
    - id: poetry-check
- repo: https://gitlab.com/pycqa/flake8
  rev: 5.0.4
  hooks:
  - id: flake8
    additional_dependencies: [flake8-bugbear]
- repo: local
  hooks:
  - id: tests
    name: tests
    entry: poetry run pytest
    language: system
    types: [python]
    pass_filenames: false